version: "3.7"

services:

  postgis:
    image: kartoza/postgis:11.0-2.5
    ports:
      - "5432"
    environment:
      POSTGRES_USER: ${QGISFEED_DOCKER_DBUSER}
      POSTGRES_PASS: ${QGISFEED_DOCKER_DBPASSWORD}
      POSTGRES_DBNAME: ${QGISFEED_DOCKER_DBNAME}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    volumes:
      - ${QGISFEED_DOCKER_SHARED_VOLUME}:/var/lib/postgresql
    networks:
      internal:

  metabase:
    image: metabase/metabase:v0.46.6.1
    hostname: metabase-secrets
    volumes:
      - /dev/urandom:/dev/random:ro
    ports:
      - 3000:3000
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_HOST: postgis
      MB_DB_USER: ${QGISFEED_DOCKER_DBUSER}
      MB_DB_PASS: ${QGISFEED_DOCKER_DBPASSWORD}
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    networks:
      internal:

  qgisfeed:
    # Note you cannot scale if you use container_name
    container_name: qgisfeed
    image: qgisfeed:production-1.3
    build:
      context: .
      dockerfile: Dockerfile.production
    environment:
      QGISFEED_DOCKER_DBNAME: ${QGISFEED_DOCKER_DBNAME}
      QGISFEED_DOCKER_DBUSER: ${QGISFEED_DOCKER_DBUSER}
      QGISFEED_DOCKER_DBPASSWORD: ${QGISFEED_DOCKER_DBPASSWORD}
      QGIS_FEED_PROD_URL: ${QGIS_FEED_PROD_URL}
      QGISFEED_FROM_EMAIL: ${QGISFEED_FROM_EMAIL:-automation}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER:-automation}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    command: /code/entrypoint_production.sh
    expose:
      - "8000"
    volumes:
      - ${QGISFEED_DOCKER_SHARED_VOLUME}:/shared-volume
      - /home/web/qgis-feed:/code
    depends_on:
      - postgis
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    restart: always
    networks:
      internal:

  nginx:
    image: nginx:latest
    ports:
      - "80:8000"
      - "443:443"
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
      - ${QGISFEED_DOCKER_SHARED_VOLUME}:/shared-volume
      - ./config/nginx:/etc/nginx/conf.d
      - ./webroot:/var/www/webroot
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
      - ./dhparam:/etc/ssl/certs
    restart: always
    networks:
      internal:

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./webroot:/var/www/webroot
      - ./certbot-etc:/etc/letsencrypt
      - ./certbot-var:/var/lib/letsencrypt
    depends_on:
      - nginx
    command: certonly --webroot --webroot-path=/var/www/webroot --email admin@qgis.org --agree-tos --no-eff-email --force-renewal -d feed.qgis.org
  
  dbbackups:
    image: kartoza/pg-backup:11.0
    environment:
      DUMPPREFIX: PG_QGIS_FEED
      POSTGRES_DATABASE: ${QGISFEED_DOCKER_DBNAME}
      POSTGRES_HOST: postgis
      POSTGRES_PASSWORD: ${QGISFEED_DOCKER_DBPASSWORD}
      POSTGRES_PORT: '5432'
      POSTGRES_USER: ${QGISFEED_DOCKER_DBUSER}
    volumes:
    - /mnt/backups/:/backups
    links:
    - postgis:postgis
    command:
    - /start.sh

networks:
    internal:

