version: '3.7'
services:
  postgis:
    image: kartoza/postgis:11.0-2.5
    platform: linux/amd64
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASS: docker
      POSTGRES_DBNAME: qgisfeed
    # ports:
    # - "5436:5432"

  qgisfeed:
    # Note you cannot scale if you use container_name
    container_name: qgisfeed
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64
    command: /code/entrypoint_testing.sh
    environment:
      DJANGO_SETTINGS_MODULE: qgisfeedproject.settings_dev
      QGISFEED_DOCKER_DBNAME: ${QGISFEED_DOCKER_DBNAME}
      QGISFEED_DOCKER_DBUSER: ${QGISFEED_DOCKER_DBUSER}
      QGISFEED_DOCKER_DBPASSWORD: ${QGISFEED_DOCKER_DBPASSWORD}
      QGISFEED_FROM_EMAIL: ${QGISFEED_FROM_EMAIL}
      EMAIL_BACKEND: ${EMAIL_BACKEND}
      EMAIL_HOST: ${EMAIL_HOST}
      EMAIL_PORT: ${EMAIL_PORT}
      EMAIL_USE_TLS: ${EMAIL_USE_TLS}
      EMAIL_HOST_USER: ${EMAIL_HOST_USER}
      EMAIL_HOST_PASSWORD: ${EMAIL_HOST_PASSWORD}
    ports:
    - "8000:8000"
    links:
      - postgis
    depends_on:
      - postgis
    volumes:
      - ../qgis-feed:/code

  webpack:
    build:
      context: .
      dockerfile: ./Dockerfile
    platform: linux/amd64 
    command: npm start
    working_dir: /code
    volumes:
      - .:/code